"""changed logic for unique order

Revision ID: 13e195690798
Revises: 8d47c0d7f0da
Create Date: 2025-03-13 15:31:02.736230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13e195690798'
down_revision: Union[str, None] = '8d47c0d7f0da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('questions_order_key', 'questions', type_='unique')
    op.create_index('ix_question_order_group', 'questions', ['order', 'group_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_question_order_group', table_name='questions')
    op.create_unique_constraint('questions_order_key', 'questions', ['order'])
    # ### end Alembic commands ###
