"""added model ruquest and added new fields for question

Revision ID: 5094dcee6ab8
Revises: 2fd901dad819
Create Date: 2025-03-14 15:14:40.466722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5094dcee6ab8'
down_revision: Union[str, None] = '2fd901dad819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
