"""added model ruquest and added new fields for question

Revision ID: 6689405667df
Revises: f38c20f48cf4
Create Date: 2025-03-14 15:00:22.886200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6689405667df'
down_revision: Union[str, None] = 'f38c20f48cf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('sub_text', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('is_required', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'is_required')
    op.drop_column('questions', 'sub_text')
    # ### end Alembic commands ###
